import 'package:flutter/material.dart';

/* Rectangle logo4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogo4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 383.0,
      height: 353.0,
    ));
  }
}
