import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedGroupWidget21.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedRectangle19Widget2.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedRectangleWidget6.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedIamalmostfinishPleasegivemeyouremailIwillZIPthemandsend.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedIcommentedonFigmaIwanttoaddsomefancyiconsDoyouhaveanyic.dart';
import 'package:deaf_project/helpers/transform/transform.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedIaminaprocessofdesigningsomeWhendoyouneedthemWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedSubtractWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedMartinaWolnaWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedRectangleWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/Generated1FEB1200Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedMaciejkowalskiemailcomWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedRectangleWidget7.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedRectangleWidget8.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedNextmonthWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedRectangleWidget5.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedWriteWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedRectangleWidget4.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedChatWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/Generated0843Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/Generated0812Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedchattingwidget/generated/GeneratedMaciejKowalskiWidget.dart';

/* Frame chatting
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChattingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(127, 24, 47, 63),
                  offset: Offset(40.0, 40.0),
                  blurRadius: 100.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 400.0,
          height: 850.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
             // overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 25.0,
                  top: 720.0,
                  right: null,
                  bottom: null,
                  width: 275.0,
                  height: 40.0,
                  child: GeneratedRectangleWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.11116666793823242;

                    final double height =
                        constraints.maxHeight * 0.02558678570915671;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.135,
                          y: constraints.maxHeight * 0.86,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedWriteWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 326.0,
                  top: 732.0,
                  right: null,
                  bottom: null,
                  width: 18.0,
                  height: 16.0,
                  child: GeneratedSubtractWidget(),
                ),
                Positioned(
                  left: 260.0,
                  top: 720.0,
                  right: null,
                  bottom: null,
                  width: 40.0,
                  height: 40.0,
                  child: GeneratedGroupWidget21(),
                ),
                Positioned(
                  left: 35.0,
                  top: 505.0,
                  right: null,
                  bottom: null,
                  width: 226.0,
                  height: 40.0,
                  child: GeneratedRectangleWidget4(),
                ),
                Positioned(
                  left: 49.0,
                  top: 505.0,
                  right: null,
                  bottom: null,
                  width: 201.0,
                  height: 45.0,
                  child: GeneratedMaciejkowalskiemailcomWidget(),
                ),
                Positioned(
                  left: 170.0,
                  top: 479.0,
                  right: null,
                  bottom: null,
                  width: 39.0,
                  height: 19.0,
                  child: Generated0843Widget(),
                ),
                Positioned(
                  left: 60.0,
                  top: 365.0,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 60.0,
                  child: GeneratedRectangleWidget5(),
                ),
                Positioned(
                  left: 71.0,
                  top: 365.0,
                  right: null,
                  bottom: null,
                  width: 251.0,
                  height: 62.0,
                  child:
                      GeneratedIamalmostfinishPleasegivemeyouremailIwillZIPthemandsend(),
                ),
                Positioned(
                  left: 170.0,
                  top: 339.0,
                  right: null,
                  bottom: null,
                  width: 39.0,
                  height: 19.0,
                  child: Generated0812Widget(),
                ),
                Positioned(
                  left: 35.0,
                  top: 285.0,
                  right: null,
                  bottom: null,
                  width: 115.0,
                  height: 40.0,
                  child: GeneratedRectangleWidget6(),
                ),
                Positioned(
                  left: 49.0,
                  top: 285.0,
                  right: null,
                  bottom: null,
                  width: 94.0,
                  height: 42.0,
                  child: GeneratedNextmonthWidget(),
                ),
                Positioned(
                  left: 95.0,
                  top: 225.0,
                  right: null,
                  bottom: null,
                  width: 245.0,
                  height: 50.0,
                  child: GeneratedRectangleWidget7(),
                ),
                Positioned(
                  left: 107.0,
                  top: 225.0,
                  right: null,
                  bottom: null,
                  width: 215.0,
                  height: 52.0,
                  child:
                      GeneratedIaminaprocessofdesigningsomeWhendoyouneedthemWidget(),
                ),
                Positioned(
                  left: 35.0,
                  top: 155.0,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 60.0,
                  child: GeneratedRectangleWidget8(),
                ),
                Positioned(
                  left: 49.0,
                  top: 155.0,
                  right: null,
                  bottom: null,
                  width: 245.0,
                  height: 62.0,
                  child:
                      GeneratedIcommentedonFigmaIwanttoaddsomefancyiconsDoyouhaveanyic(),
                ),
                Positioned(
                  left: 150.0,
                  top: 129.0,
                  right: null,
                  bottom: null,
                  width: 76.0,
                  height: 16.0,
                  child: Generated1FEB1200Widget(),
                ),
                Positioned(
                  left: 218.0,
                  top: 76.0,
                  right: null,
                  bottom: null,
                  width: 124.0,
                  height: 20.0,
                  child: GeneratedMaciejKowalskiWidget(),
                ),
                Positioned(
                  left: 230.0,
                  top: 51.0,
                  right: null,
                  bottom: null,
                  width: 112.0,
                  height: 20.0,
                  child: GeneratedMartinaWolnaWidget(),
                ),
                Positioned(
                  left: -3.0,
                  top: -9.0,
                  right: null,
                  bottom: null,
                  width: 413.0,
                  height: 98.0,
                  child: GeneratedRectangle19Widget2(),
                ),
                Positioned(
                  left: 20.0,
                  top: 40.0,
                  right: null,
                  bottom: null,
                  width: 81.0,
                  height: 34.0,
                  child: GeneratedChatWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
