// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjoDXjhDhkUMDiijKHC4sWcp86tQaQNbk',
    appId: '1:116713944482:web:a135a7d3b56ee7cfcf6efb',
    messagingSenderId: '116713944482',
    projectId: 'new-deaf',
    authDomain: 'new-deaf.firebaseapp.com',
    storageBucket: 'new-deaf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv_FAeWlncjAkAxHFN_-hHAEEGE4JQPS4',
    appId: '1:116713944482:android:1595b291bc8cfa91cf6efb',
    messagingSenderId: '116713944482',
    projectId: 'new-deaf',
    storageBucket: 'new-deaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6OhAY2fnukuTLXNS2dtD5OfxYvb9VpOE',
    appId: '1:116713944482:ios:dc735be0fbddb298cf6efb',
    messagingSenderId: '116713944482',
    projectId: 'new-deaf',
    storageBucket: 'new-deaf.appspot.com',
    iosClientId: '116713944482-lu7cptmd8h5tm62bskda4ebbg6bq1gf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6OhAY2fnukuTLXNS2dtD5OfxYvb9VpOE',
    appId: '1:116713944482:ios:dc735be0fbddb298cf6efb',
    messagingSenderId: '116713944482',
    projectId: 'new-deaf',
    storageBucket: 'new-deaf.appspot.com',
    iosClientId: '116713944482-lu7cptmd8h5tm62bskda4ebbg6bq1gf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegister',
  );
}
