// import 'package:flutter/material.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedLastNameWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedContinuewithGoogleLeftAlignedFixedWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedSIGNUPWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedFirstNameWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedLine6Widget1.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedContinuewithFacebookLeftAlignedFixedWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedalreadyhaveanaccountSIGNINWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedRectangle3Widget1.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedRectangle2Widget3.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedContinuewithAppleLeftAlignedFixedWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedPasswordWidget1.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedPleaseenteryourdetailsWidget1.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedLine8Widget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedCreateanaccountWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedLine7Widget1.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedLine9Widget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedSignupWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedEmailWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedLine13Widget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedorsignupwithWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedWhatsApp_Image_20230205_at_12091Widget2.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsignupwidget/generated/GeneratedUsetryWidget.dart';

// /* Frame signUp
//     Autogenerated by FlutLab FTF Generator
//   */
// class GeneratedSignUpWidget extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Material(
//         child: ClipRRect(
//       borderRadius: BorderRadius.zero,
//       child: Container(
//         width: 400.0,
//         height: 850.0,
//         child: Stack(
//             fit: StackFit.expand,
//             alignment: Alignment.center,
//            // overflow: Overflow.visible,
//             children: [
//               ClipRRect(
//                 borderRadius: BorderRadius.zero,
//                 child: Container(
//                   color: Color.fromARGB(255, 255, 255, 255),
//                 ),
//               ),
//               Positioned(
//                 left: 24.0,
//                 top: 205.0,
//                 right: null,
//                 bottom: null,
//                 width: 383.0,
//                 height: 353.0,
//                 child: GeneratedWhatsApp_Image_20230205_at_12091Widget2(),
//               ),
//               Positioned(
//                 left: 11.72137451171875,
//                 top: -369.0,
//                 right: null,
//                 bottom: null,
//                 width: 303.1432800292969,
//                 height: 485.87896728515625,
//                 child: GeneratedRectangle3Widget1(),
//               ),
//               Positioned(
//                 left: 115.0,
//                 top: 76.0,
//                 right: null,
//                 bottom: null,
//                 width: 204.0,
//                 height: 46.0,
//                 child: GeneratedSignupWidget(),
//               ),
//               Positioned(
//                 left: 55.0,
//                 top: 256.0,
//                 right: null,
//                 bottom: null,
//                 width: 543.0,
//                 height: 43.0,
//                 child: GeneratedPleaseenteryourdetailsWidget1(),
//               ),
//               Positioned(
//                 left: 79.0,
//                 top: 390.0,
//                 right: null,
//                 bottom: null,
//                 width: 227.0,
//                 height: 1.0,
//                 child: GeneratedLine6Widget1(),
//               ),
//               Positioned(
//                 left: 80.0,
//                 top: 441.0,
//                 right: null,
//                 bottom: null,
//                 width: 104.0,
//                 height: 29.0,
//                 child: GeneratedPasswordWidget1(),
//               ),
//               Positioned(
//                 left: 79.0,
//                 top: 482.0,
//                 right: null,
//                 bottom: null,
//                 width: 227.0,
//                 height: 1.0,
//                 child: GeneratedLine7Widget1(),
//               ),
//               Positioned(
//                 left: 127.0,
//                 top: 539.0,
//                 right: null,
//                 bottom: null,
//                 width: 149.0,
//                 height: 60.0,
//                 child: GeneratedRectangle2Widget3(),
//               ),
//               Positioned(
//                 left: 163.0,
//                 top: 558.0,
//                 right: null,
//                 bottom: null,
//                 width: 84.0,
//                 height: 47.0,
//                 child: GeneratedSIGNUPWidget(),
//               ),
//               Positioned(
//                 left: 79.0,
//                 top: 376.0,
//                 right: null,
//                 bottom: null,
//                 width: 57.0,
//                 height: 50.0,
//                 child: GeneratedEmailWidget(),
//               ),
//               Positioned(
//                 left: 79.0,
//                 top: 434.0,
//                 right: null,
//                 bottom: null,
//                 width: 227.0,
//                 height: 1.0,
//                 child: GeneratedLine8Widget(),
//               ),
//               Positioned(
//                 left: 80.0,
//                 top: 347.0,
//                 right: null,
//                 bottom: null,
//                 width: 227.0,
//                 height: 1.0,
//                 child: GeneratedLine9Widget(),
//               ),
//               Positioned(
//                 left: 79.0,
//                 top: 354.0,
//                 right: null,
//                 bottom: null,
//                 width: 101.0,
//                 height: 29.0,
//                 child: GeneratedLastNameWidget(),
//               ),
//               Positioned(
//                 left: 101.0,
//                 top: 197.0,
//                 right: null,
//                 bottom: null,
//                 width: 182.0,
//                 height: 26.0,
//                 child: GeneratedCreateanaccountWidget(),
//               ),
//               Positioned(
//                 left: 79.0,
//                 top: 316.0,
//                 right: null,
//                 bottom: null,
//                 width: 109.0,
//                 height: 29.0,
//                 child: GeneratedFirstNameWidget(),
//               ),
//               Positioned(
//                 left: 105.0,
//                 top: 636.0,
//                 right: null,
//                 bottom: null,
//                 width: 192.0,
//                 height: 26.0,
//                 child: GeneratedorsignupwithWidget(),
//               ),
//               Positioned(
//                 left: 43.0,
//                 top: 681.0,
//                 right: null,
//                 bottom: null,
//                 width: 52.0,
//                 height: 53.0,
//                 child: GeneratedContinuewithFacebookLeftAlignedFixedWidget(),
//               ),
//               Positioned(
//                 left: 172.0,
//                 top: 681.0,
//                 right: null,
//                 bottom: null,
//                 width: 56.0,
//                 height: 53.0,
//                 child: GeneratedContinuewithGoogleLeftAlignedFixedWidget(),
//               ),
//               Positioned(
//                 left: 282.0,
//                 top: 681.0,
//                 right: null,
//                 bottom: null,
//                 width: 56.0,
//                 height: 53.0,
//                 child: GeneratedContinuewithAppleLeftAlignedFixedWidget(),
//               ),
//               Positioned(
//                 left: 20.0,
//                 top: 771.0,
//                 right: null,
//                 bottom: null,
//                 width: 354.0,
//                 height: 26.0,
//                 child: GeneratedalreadyhaveanaccountSIGNINWidget(),
//               ),
//               Positioned(
//                 left: 290.0,
//                 top: 795.0,
//                 right: null,
//                 bottom: null,
//                 width: 57.0,
//                 height: 1.0,
//                 child: GeneratedLine13Widget(),
//               ),
//               Positioned(
//                 left: 161.0,
//                 top: 802.0,
//                 right: null,
//                 bottom: null,
//                 width: 117.0,
//                 height: 35.0,
//                 child: GeneratedUsetryWidget(),
//               )
//             ]),
//       ),
//     ));
//   }
// }
