import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:deaf_project/easy_20meetapp/SignUp.dart';
import 'package:deaf_project/easy_20meetapp/generatedsplashwidget/generated/GeneratedEasyMeetWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedsplashwidget/generated/GeneratedWhatsApp_Image_20230424_at_8031Widget.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

/* Frame splash
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashWidget extends StatefulWidget {
  @override
  State<GeneratedSplashWidget> createState() => _GeneratedSplashWidgetState();
}

class _GeneratedSplashWidgetState extends State<GeneratedSplashWidget> {
  @override
  void initState() {
    Timer(
      Duration(seconds: 2),
      () {
        Get.offAll(()=> SignUp(),
        duration: Duration(milliseconds: 1250),
            transition: Transition.rightToLeft, curve: Curves.easeInOutCubic);
    
      },
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 412.0,
          height: 850.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              // overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 97, 29, 139),
                  ),
                ),
                Positioned(
                  left: 96.0,
                  top: 314.0,
                  right: null,
                  bottom: null,
                  width: 200.0,
                  height: 111.8541030883789,
                  child: GeneratedWhatsApp_Image_20230424_at_8031Widget(),
                ),
                Positioned(
                  left: 110.0,
                  top: 400.0,
                  right: null,
                  bottom: null,
                  width: 205.0,
                  height: 105.0,
                  child: GeneratedEasyMeetWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
