import 'package:flutter/material.dart';
import 'package:deaf_project/easy_20meetapp/generatedmeet_join_idwidget/generated/GeneratedGroup13Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmeet_join_idwidget/generated/GeneratedLine6Widget2.dart';
import 'package:deaf_project/easy_20meetapp/generatedmeet_join_idwidget/generated/GeneratedNameWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmeet_join_idwidget/generated/GeneratedIDWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmeet_join_idwidget/generated/GeneratedWhatsApp_Image_20230424_at_8032Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmeet_join_idwidget/generated/GeneratedLine7Widget2.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

/* Frame meet_join_id
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMeet_join_idWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(73, 25, 27, 26),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 20.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 400.0,
          height: 850.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
             // overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 50.0,
                  top: 274.0,
                  right: null,
                  bottom: null,
                  width: 112.0,
                  height: 49.0,
                  child: GeneratedIDWidget(),
                ),
                Positioned(
                  left: 50.0,
                  top: 318.0,
                  right: null,
                  bottom: null,
                  width: 227.0,
                  height: 1.0,
                  child: GeneratedLine6Widget2(),
                ),
                Positioned(
                  left: 50.0,
                  top: 395.0,
                  right: null,
                  bottom: null,
                  width: 227.0,
                  height: 1.0,
                  child: GeneratedLine7Widget2(),
                ),
                Positioned(
                  left: 50.0,
                  top: 345.0,
                  right: null,
                  bottom: null,
                  width: 63.0,
                  height: 29.0,
                  child: GeneratedNameWidget(),
                ),
                Positioned(
                  left: 46.0,
                  top: 493.0,
                  right: null,
                  bottom: null,
                  width: 373.0,
                  height: 251.0,
                  child: GeneratedGroup13Widget(),
                ),
                Positioned(
                  left: 79.0,
                  top: 82.0,
                  right: null,
                  bottom: null,
                  width: 292.0,
                  height: 181.0,
                  child: GeneratedWhatsApp_Image_20230424_at_8032Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
