import 'package:deaf_project/easy_20meetapp/generatedmainwidget/generated/GeneratedGroup19Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmainwidget/generated/GeneratedGroup21Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmainwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmainwidget/generated/GeneratedRectangle14Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmainwidget/generated/GeneratedRectangle16Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmainwidget/generated/GeneratedRectangle18Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmainwidget/generated/GeneratedRectangle3Widget2.dart';
import 'package:deaf_project/easy_20meetapp/generatedmainwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmainwidget/generated/GeneratedRectangle8Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmainwidget/generated/GeneratedWhatsApp_Image_20230210_at_7211Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmainwidget/generated/GeneratedWhatsApp_Image_20230210_at_7261Widget.dart';
import 'package:deaf_project/helpers/transform/transform.dart';
import 'package:flutter/material.dart';

/* Frame main
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 400.0,
        height: 850.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
           // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 1.001116081686581;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle3Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: -8.0,
                top: 777.0,
                right: null,
                bottom: null,
                width: 415.0,
                height: 82.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 804.0,
                right: null,
                bottom: null,
                width: 319.6639709472656,
                height: 41.86088562011719,
                child: GeneratedGroup19Widget(),
              ),
              Positioned(
                left: -2.0,
                top: -8.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 85.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 158.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 232.1244659423828,
                height: 45.0,
                child: GeneratedGroup21Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 192.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 147.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 165.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 192.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 192.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 183.0,
                child: GeneratedWhatsApp_Image_20230210_at_7211Widget(),
              ),
              Positioned(
                left: 126.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 182.0,
                child: GeneratedWhatsApp_Image_20230210_at_7261Widget(),
              )
            ]),
      ),
    ));
  }
}
