import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:deaf_project/easy_20meetapp/generatedsign_textwidget/generated/GeneratedRectangle11Widget1.dart';
import 'package:deaf_project/easy_20meetapp/generatedsign_textwidget/generated/GeneratedFrame2Widget3.dart';
import 'package:deaf_project/easy_20meetapp/generatedsign_textwidget/generated/GeneratedRectangle8Widget1.dart';
import 'package:deaf_project/easy_20meetapp/generatedsign_textwidget/generated/GeneratedSigntotextWidget1.dart';
import 'package:deaf_project/easy_20meetapp/generatedsign_textwidget/generated/GeneratedRectangle19Widget3.dart';

/* Frame sign_text
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSign_textWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(73, 25, 27, 26),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 20.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 400.0,
          height: 850.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
             // overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -13.0,
                  top: -9.0,
                  right: null,
                  bottom: null,
                  width: 413.0,
                  height: 98.0,
                  child: GeneratedRectangle19Widget3(),
                ),
                Positioned(
                  left: 30.0,
                  top: 49.0,
                  right: null,
                  bottom: null,
                  width: 210.0,
                  height: 42.0,
                  child: GeneratedSigntotextWidget1(),
                ),
                Positioned(
                  left: -13.0,
                  top: 89.0,
                  right: null,
                  bottom: null,
                  width: 449.0,
                  height: 303.0,
                  child: GeneratedRectangle11Widget1(),
                ),
                Positioned(
                  left: -32.0,
                  top: 162.0,
                  right: null,
                  bottom: null,
                  width: 379.0,
                  height: 230.0,
                  child: GeneratedRectangle8Widget1(),
                ),
                Positioned(
                  left: 30.0,
                  top: 484.0,
                  right: null,
                  bottom: null,
                  width: 336.0,
                  height: 283.0,
                  child: GeneratedFrame2Widget3(),
                )
              ]),
        ),
      ),
    ));
  }
}
