import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:deaf_project/easy_20meetapp/generatedmeetingwidget/generated/GeneratedFrame1Widget1.dart';
import 'package:deaf_project/easy_20meetapp/generatedmeetingwidget/generated/GeneratedTABLEWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmeetingwidget/generated/GeneratedLAMPWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmeetingwidget/generated/GeneratedGIRLWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmeetingwidget/generated/GeneratedFrame2Widget1.dart';
import 'package:deaf_project/easy_20meetapp/generatedmeetingwidget/generated/GeneratedCOMPUTERWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedmeetingwidget/generated/GeneratedLIGHTWidget.dart';
import 'package:deaf_project/helpers/transform/transform.dart';

/* Frame Meeting
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMeetingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(73, 25, 27, 26),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 20.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 400.0,
          height: 850.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
             // overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 36.0,
                  top: 526.0,
                  right: null,
                  bottom: null,
                  width: 340.0,
                  height: 51.0,
                  child: GeneratedFrame1Widget1(),
                ),
                Positioned(
                  left: 36.0,
                  top: 614.0,
                  right: null,
                  bottom: null,
                  width: 340.0,
                  height: 51.0,
                  child: GeneratedFrame2Widget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.6635527801513672;

                    final double height =
                        constraints.maxHeight * 0.18278036678538603;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.16290534973144533,
                          y: constraints.maxHeight * 0.10607866175034467,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedLAMPWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.37078224182128905;

                    final double height =
                        constraints.maxHeight * 0.13808275110581342;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.1674032402038574,
                          y: constraints.maxHeight * 0.15050397087545955,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedCOMPUTERWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.7888494873046875;

                    final double height =
                        constraints.maxHeight * 0.1709245928596048;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.07542579174041748,
                          y: constraints.maxHeight * 0.2888590913660386,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedTABLEWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.3752798080444336;

                    final double height =
                        constraints.maxHeight * 0.13808275110581342;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.16293386459350587,
                          y: constraints.maxHeight * 0.15050397087545955,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedLIGHTWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.43869915008544924;

                    final double height =
                        constraints.maxHeight * 0.2947011790556066;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.30199541091918947,
                          y: constraints.maxHeight * 0.16508241541245405,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGIRLWidget(),
                          ))
                    ]);
                  }),
                )
              ]),
        ),
      ),
    ));
  }
}
