import 'package:deaf_project/easy_20meetapp/generatedspeech_textwidget/generated/GeneratedClickingthemicrophonebuttonwillstartavoicememorecording1.dart';
import 'package:deaf_project/easy_20meetapp/generatedspeech_textwidget/generated/GeneratedImage11Widget1.dart';
import 'package:deaf_project/easy_20meetapp/generatedspeech_textwidget/generated/GeneratedRectangle19Widget1.dart';
import 'package:deaf_project/easy_20meetapp/generatedspeech_textwidget/generated/GeneratedSpeechtotextWidget2.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

/* Frame speech_text
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSpeech_textWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(73, 25, 27, 26),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 20.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 400.0,
          height: 850.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
             // overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 94.0,
                  top: 598.0,
                  right: null,
                  bottom: null,
                  width: 212.0,
                  height: 212.0,
                  child: GeneratedImage11Widget1(),
                ),
                Positioned(
                  left: 59.0,
                  top: 265.0,
                  right: null,
                  bottom: null,
                  width: 319.0,
                  height: 82.0,
                  child:
                      GeneratedClickingthemicrophonebuttonwillstartavoicememorecording1(),
                ),
                Positioned(
                  left: -13.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 413.0,
                  height: 98.0,
                  child: GeneratedRectangle19Widget1(),
                ),
                Positioned(
                  left: 24.0,
                  top: 58.0,
                  right: null,
                  bottom: null,
                  width: 210.0,
                  height: 42.0,
                  child: GeneratedSpeechtotextWidget2(),
                )
              ]),
        ),
      ),
    ));
  }
}
