import 'package:deaf_project/easy_20meetapp/generatedintro1widget/generated/GeneratedIntro1Widget1.dart';
import 'package:deaf_project/easy_20meetapp/generatedintro1widget/generated/GeneratedMeetWithoutWorryingaboutLanguageWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedintro1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedintro1widget/generated/GeneratedRectangle2Widget.dart';
import 'package:deaf_project/easy_20meetapp/generatedintro1widget/generated/GeneratedTryEasyMeetNowWidget.dart';
import 'package:deaf_project/easy_20meetapp/generatedintro1widget/generated/GeneratedUseeasymeettogetnewexperienceindoingvideomeetdontworrya.dart';
import 'package:deaf_project/easy_20meetapp/generatedintro1widget/generated/GeneratedWhatchTheDemoWidget.dart';
import 'package:flutter/material.dart';

/* Frame intro1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntro1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 400.0,
        height: 850.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
           // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 21.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 205.0,
                height: 83.0,
                child: GeneratedMeetWithoutWorryingaboutLanguageWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 152.0,
                child:
                    GeneratedUseeasymeettogetnewexperienceindoingvideomeetdontworrya(),
              ),
              Positioned(
                left: 187.53146362304688,
                top: 16.0,
                right: null,
                bottom: null,
                width: 205.84640502929688,
                height: 141.12411499023438,
                child: GeneratedIntro1Widget1(),
              ),
              Positioned(
                left: 56.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 73.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 81.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 31.0,
                child: GeneratedTryEasyMeetNowWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 68.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 83.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 41.0,
                child: GeneratedWhatchTheDemoWidget(),
              )
            ]),
      ),
    ));
  }
}
