// import 'package:flutter/material.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedPleaseenteryourdetailsWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedLine6Widget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedUsernameWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedSignINWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedWelcomebackWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedLine11Widget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedRectangle2Widget2.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedRectangle4Widget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedImage2Widget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedLine12Widget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedLine7Widget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedPasswordWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedWhatsApp_Image_20230205_at_12091Widget1.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedRemembermeWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedLine10Widget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedRectangle3Widget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedSIGNINWidget.dart';
// import 'package:flutterapp/easy_20meetapp/generatedsigninwidget/generated/GeneratedForgetpasswordWidget.dart';

// /* Frame signIn
//     Autogenerated by FlutLab FTF Generator
//   */
// class GeneratedSignInWidget extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Material(
//         child: ClipRRect(
//       borderRadius: BorderRadius.zero,
//       child: Container(
//         width: 400.0,
//         height: 850.0,
//         child: Stack(
//             fit: StackFit.expand,
//             alignment: Alignment.center,
//            // overflow: Overflow.visible,
//             children: [
//               ClipRRect(
//                 borderRadius: BorderRadius.zero,
//                 child: Container(
//                   color: Color.fromARGB(255, 255, 255, 255),
//                 ),
//               ),
//               Positioned(
//                 left: 24.0,
//                 top: 205.0,
//                 right: null,
//                 bottom: null,
//                 width: 383.0,
//                 height: 353.0,
//                 child: GeneratedWhatsApp_Image_20230205_at_12091Widget1(),
//               ),
//               Positioned(
//                 left: 11.72137451171875,
//                 top: -369.0,
//                 right: null,
//                 bottom: null,
//                 width: 303.1432800292969,
//                 height: 485.87896728515625,
//                 child: GeneratedRectangle3Widget(),
//               ),
//               Positioned(
//                 left: 115.0,
//                 top: 76.0,
//                 right: null,
//                 bottom: null,
//                 width: 204.0,
//                 height: 46.0,
//                 // child: GeneratedSignINWidget(),
//               ),
//               Positioned(
//                 left: 46.0,
//                 top: 255.0,
//                 right: null,
//                 bottom: null,
//                 width: 543.0,
//                 height: 29.0,
//                 child: GeneratedPleaseenteryourdetailsWidget(),
//               ),
//               Positioned(
//                 left: 66.0,
//                 top: 326.0,
//                 right: null,
//                 bottom: null,
//                 width: 109.0,
//                 height: 46.0,
//                 child: GeneratedUsernameWidget(),
//               ),
//               Positioned(
//                 left: 66.0,
//                 top: 370.0,
//                 right: null,
//                 bottom: null,
//                 width: 227.0,
//                 height: 1.0,
//                 child: GeneratedLine6Widget(),
//               ),
//               Positioned(
//                 left: 66.0,
//                 top: 447.0,
//                 right: null,
//                 bottom: null,
//                 width: 227.0,
//                 height: 1.0,
//                 child: GeneratedLine7Widget(),
//               ),
//               Positioned(
//                 left: 127.0,
//                 top: 658.0,
//                 right: null,
//                 bottom: null,
//                 width: 149.0,
//                 height: 67.0,
//                 child: GeneratedRectangle2Widget2(),
//               ),
//               Positioned(
//                 left: 166.0,
//                 top: 683.0,
//                 right: null,
//                 bottom: null,
//                 width: 88.0,
//                 height: 65.0,
//                 child: GeneratedSIGNINWidget(),
//               ),
//               Positioned(
//                 left: 66.0,
//                 top: 397.0,
//                 right: null,
//                 bottom: null,
//                 width: 104.0,
//                 height: 29.0,
//                 child: GeneratedPasswordWidget(),
//               ),
//               Positioned(
//                 left: 127.0,
//                 top: 193.0,
//                 right: null,
//                 bottom: null,
//                 width: 146.0,
//                 height: 26.0,
//                 child: GeneratedWelcomebackWidget(),
//               ),
//               Positioned(
//                 left: 65.0,
//                 top: 491.0,
//                 right: null,
//                 bottom: null,
//                 width: 143.0,
//                 height: 25.0,
//                 child: GeneratedRemembermeWidget(),
//               ),
//               Positioned(
//                 left: 180.0,
//                 top: 485.0,
//                 right: null,
//                 bottom: null,
//                 width: 29.0,
//                 height: 30.0,
//                 child: GeneratedRectangle4Widget(),
//               ),
//               Positioned(
//                 left: 186.0,
//                 top: 494.0,
//                 right: null,
//                 bottom: null,
//                 width: 14.03566837310791,
//                 height: 1.0,
//                 child: GeneratedLine10Widget(),
//               ),
//               Positioned(
//                 left: 187.0,
//                 top: 508.0,
//                 right: null,
//                 bottom: null,
//                 width: 24.83948516845703,
//                 height: 1.0,
//                 child: GeneratedLine11Widget(),
//               ),
//               Positioned(
//                 left: 206.0,
//                 top: 402.0,
//                 right: null,
//                 bottom: null,
//                 width: 73.0,
//                 height: 31.0,
//                 child: GeneratedWidget(),
//               ),
//               Positioned(
//                 left: 246.0,
//                 top: 535.0,
//                 right: null,
//                 bottom: null,
//                 width: 156.0,
//                 height: 43.0,
//                 child: GeneratedForgetpasswordWidget(),
//               ),
//               Positioned(
//                 left: 253.0,
//                 top: 558.0,
//                 right: null,
//                 bottom: null,
//                 width: 112.0,
//                 height: 1.0,
//                 child: GeneratedLine12Widget(),
//               ),
//               Positioned(
//                 left: 582.0,
//                 top: 2214.0,
//                 right: null,
//                 bottom: null,
//                 width: 800.0,
//                 height: 1704.0,
//                 child: GeneratedImage2Widget(),
//               )
//             ]),
//       ),
//     ));
//   }
// }
